name: Build and Deploy

on: 
  push:
    branches: ['**']  # Run on all branches
  pull_request:
    branches: [main]  # Run on PRs to main

permissions:
  contents: write
  pull-requests: write  # Allows commenting on PRs

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - name: 'checkout'
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: 'build'
        uses: shalzz/zola-deploy-action@master
        env:
          PAGES_BRANCH: gh-pages
          BUILD_DIR: .
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BUILD_ONLY: true
          
  build_and_deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: 'checkout'
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: 'build and deploy'
        uses: shalzz/zola-deploy-action@master
        env:
          PAGES_BRANCH: gh-pages
          BUILD_DIR: .
          TOKEN: ${{ secrets.DEPLOY_TOKEN }}
